use utoipa::ToSchema;
/*
 * Blockchain API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct QueryAmount {
    /// The amount of currency in the wallet for the provided address
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
}

impl QueryAmount {
    pub fn new() -> QueryAmount {
        QueryAmount {
            amount: None,
        }
    }
}

