/*
 * Blockchain API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::apis::dto::Transaction;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct TransactionsInBlockChainResponse {
    #[serde(rename = "transaction_count", skip_serializing_if = "Option::is_none")]
    pub transaction_count: Option<i32>,
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<Transaction>>,
}

impl TransactionsInBlockChainResponse {
    pub fn new() -> TransactionsInBlockChainResponse {
        TransactionsInBlockChainResponse {
            transaction_count: None,
            transactions: None,
        }
    }
}
