/*
 * Blockchain API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct WalletResponse {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "publicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    #[serde(rename = "privateKey", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
}

impl WalletResponse {
    pub fn new() -> WalletResponse {
        WalletResponse {
            address: None,
            public_key: None,
            private_key: None,
        }
    }

    pub fn new_from(address: String, public_key: String, private_key: String) -> WalletResponse {
        WalletResponse {
            address: Some(address),
            public_key: Some(public_key),
            private_key: Some(private_key),
        }
    }
}

