openapi: 3.0.0
info:
  title: Blockchain API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /wallet:
    get:
      tags:
        - Wallet
      summary: Get Wallet Information
      operationId: getWalletData
      responses:
        "200":
          description: Wallet information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletResponse"
    post:
      tags:
        - Wallet
      summary: Create a new wallet
      operationId: createWallet
      responses:
        "201":
          description: Wallet created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletResponse"
  /blockchain/transaction:
    post:
      tags:
        - Blockchain
      summary: Add a transaction to the blockchain
      operationId: addTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionRequest"
      responses:
        "200":
          description: Transaction added successfully
  /blockchain/transactions:
    get:
      tags:
        - Blockchain
      summary: Show all transactions in the blockchain
      operationId: showTransactions
      responses:
        "200":
          description: Transactions retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionsInBlockChainResponse"
  /blockchain/amount/{address}:
    get:
      tags:
        - Blockchain
      summary: Get total amount for an address
      operationId: getAmount
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
          description: The blockchain address to query
      responses:
        "200":
          description: Amount retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryAmountResponse"
components:
  schemas:
    WalletResponse:
      type: object
      properties:
        address:
          type: string
        public_key:
          type: string
        private_key:
          type: string
    TransactionRequest:
      type: object
      properties:
        recipient:
          type: string
        amount:
          type: number
          format: float
    Transaction:
      type: object
      properties:
        sender:
          type: string
        recipient:
          type: string
        amount:
          type: number
          format: float
        publicKey:
          type: string
        signature:
          type: string
    QueryAmountResponse:
      type: object
      properties:
        amount:
          type: number
          format: float
    TransactionsInBlockChainResponse:
      type: object
      properties:
        transaction_count:
          type: integer
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/Transaction"
